const courseURL = "/api/courses/";
const loginURL = "/api/login";
const university = "/api/universities";
const String basicUrl = "http://178.128.60.34";
const teacherURL = "/api/teachers/";
const locationURL = "/api/locations/";
const sessionURL = "/api/sessions";
const uploadURL = "/api/upload";
const usersURL = "/api/users";
